# Generated by Django 4.2.13 on 2026-06-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fit_signal",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="review_summary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
